var config={
	blankId:'#blank',
	bodyId:'#wrap',
	holder:'#holder',
	popUpId:'#window-popup',
	topNav:'#top-nav',
	controlId:'#control-panel',
	confirmId:'#window-confirm',
	windowMessage:'#window-message',
	domain:'http://f0287734.xsph.ru',
	html:{
		errorFavicon:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAASFBMVEVHcExtdrBfaqmBiLpha6lSXaF5grZDT5lOWZ5eaahzfLNsda96grdye7J7g7euuNX////FzeK8xd3w8/rY3u3k6PSYpMj8/f+inH0FAAAAD3RSTlMAiOLs8f1RHwnWvYjsvVByJ79pAAAAkUlEQVQY02WPVxLDIAxEbdNMcVQQcP+bRsBkJpPs3z6VlY7jX3fwyTpnkw/39mc0vXcy8VwknFcHrg0bXzko8JFA1XAwR68gmTFBxQpSHgWW6vI4BMgqcIIs6hEZxE3QsPI3sKTdRNQQ6xpJRotzjRbWUo3dAAatWD1MiQAI7cPukGMh7r3E/HnGP/O557X9j94tfwnWf6UiBQAAAABJRU5ErkJggg==',
		closeIcon:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOAQMAAAAlhr+SAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAACpJREFUCNdjcOBgeCDDUGDBYFHAIPOAgf8AA3sDCAEZQC5QECgFVODAAQDM9AnNrYQqKQAAAABJRU5ErkJggg==',
		editName:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOAQMAAAAlhr+SAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURUdwTP///5+UokMAAAABdFJOUwBA5thmAAAAMklEQVQI12NgEGBgkGBgyGFg+MDAWMDAvICB/QADfwODPAODHQNDDQPDDAaGCQwMDxgAfbkG0LxSfykAAAAASUVORK5CYII=',
		openAll:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOBAMAAADtZjDiAAAAHlBMVEX///////////////9HcEz///////////////////8nJIQvAAAACnRSTlPVwj2pAIp0WOYk2dH38QAAAGpJREFUCNdjcAEC5YYUBiDlLsHQBqILWdUZgLRncqYTB5BWC1WZ2szg4m7QkJQgxOBSyGgcyljC4C4Qaiwg7sKgyKrGwVziwmAR6RSa5OLC0KAyzWwKkGYoChAHmsWQwdBYAqLdOIxAVgEAjNkZb4egJwEAAAAASUVORK5CYII=',
		addLink:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOAQMAAAAlhr+SAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURUdwTP///5+UokMAAAABdFJOUwBA5thmAAAAE0lEQVQI12Ngb2BARv//IBCqFAAS/A0zi/Ht3QAAAABJRU5ErkJggg==',
	},
	templaters:{
		popUpId:'templater/popUpId.tpl',
		bodyId:'templater/bodyId.tpl',
		topNavLog:'templater/topNavLog.tpl',
		topNav:'templater/topNav.tpl',
		bodyFailedAuth:'templater/bodyFailedAuth.tpl',
		registration:'templater/registration.tpl',
		login:'templater/login.tpl',
		syncToServ:'templater/syncToServ.tpl',
		syncToPc:'templater/syncToPc.tpl',
		emptySearch:'templater/emptySearch.tpl',
		updateButton:'templater/updateButton.tpl',
		notification:'templater/notification.tpl'
	}
};
for(key in config.templaters){
	(function(key,value){
		fetch(value,{
			cache:'force-cache'
		}).then(function(response){
			return response.text();
		}).then(function(response){
			config.html[key]=response;
		});
	})(key,config.templaters[key]);
}